### ISSUE TITLE
Auth problem

### ISSUE THREAD

**Issue by Rudzix77** [BorlCand/bungeecord-rcon#1]
Hey,

First of all my auto-generated config looks weird:

> Rcon:
>   Enabled: true
>   Port: 39999
>   Password: '12fsdaf5s4f5asdf3456'
>   Colored: true
> Rcon_Enabled: true
> Rcon_Port: 39999
> Rcon_Password: '12fsdaf5s4f5asdf3456'
> Rcon_Colored: true

And when I'm trying to connect using my tested node.js lib there is problem with authentication. The plugin is launching on start of Bungee and saying that is binding port 39999 and my library hasn't got problem to connect but with auth.

Could you check if something is wrong? I am using newest bungeeCord 

After change to your version of Yumler, config looks fine but it still can't auth well

**Comment by marzenie** [comment]
@Rudzix77  Hi 
did you handle it 'Cause I guess I have the same problem

**Comment by andreypuhovsky** [comment]
Sorry, since I've retired from developing for Minecraft-related things you can fork the repository and fix it on your own (if there's no such other plugin)
In #3 there were changes required to work with 1.19+ versions. Please try it.
